### ISSUE TITLE
Participants array is empty

### ISSUE THREAD

**Issue by ShriramK** [Jana-Mobile/layer-python#7] opened 2016-07-02 14:28 UTC
Once the message is sent using send_message ,
 the conversation dict of the response 
shows neither the sender nor the recipient in it.
is this by design ?

**Comment by rschlaikjer** [comment] 2016-07-02 14:34
It looks like the `send_message` call should be getting JSON back from layer containing both `sender` and `recipient_status` (see https://developer.layer.com/docs/platform/messages#sending-messages), which should be getting parsed here:
https://github.com/Jana-Mobile/layer-python/blob/master/LayerClient/LayerClient.py#L370
Can you take a look at the raw response from Layer and check that it contains these fields?

**Comment by ShriramK** [comment] 2016-07-02 15:20
![layerapicallparticipantserror1](https://cloud.githubusercontent.com/assets/780653/16541043/80ef3bcc-4096-11e6-9831-e0d61ab0d56b.jpg)

**Comment by rschlaikjer** [comment] 2016-07-02 17:23
Hm, it's a little unclear what's going on there. Looks like the top conversation has that data but the bottom doesn't?

Can you post a small script that can be used to replicate the issue, or the raw JSON being returned from the Layer API that's causing an issue?

**Comment by ShriramK** [comment] 2016-07-02 17:35
It's the same script that's posted under Usage in https://github.com/Jana-Mobile/

**Comment by rschlaikjer** [comment] 2016-07-02 17:47
Ah, I see what you mean - yes; as per the API docs (linked in my first reply), the conversation returned with the message does not contain any information other than `id` and `url`. So yes; this is by design.

If you wanted to have the full conversation object as part of the message, you could either keep a reference to the original conversation and assign it, or re-fetch the full conversation like so:

```
Python 2.7.11+ (default, Apr 17 2016, 14:00:29)
[GCC 5.3.1 20160409] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> APP_ID = 'snip'
>>> TOKEN = 'snip'
>>> from LayerClient import LayerClient
>>> client = LayerClient.PlatformClient(APP_ID, TOKEN)
>>> sender = LayerClient.Sender(
...     id='alice',
...     name='Alice',
... )
>>> receiver = LayerClient.Sender(
...     id='bob',
...     name='Bob',
... )
>>> conversation = client.create_conversation(
...     [
...         sender.id,
...         receiver.id,
...     ],
...     distinct=True,
...     metadata={
...         'background_color': '#3c3c3c',
...         'title': 'A test conversaton',
...     }
... )
>>> message_parts = [
...     LayerClient.MessagePart(
...         'Sure is nice to not talk about Crypto for a change!'
...     ),
... ]
>>> conversation.participants
[u'alice', u'bob']
>>> notification = LayerClient.PushNotification(
...     'You got a message from Alice!'
... )
>>> message_resp = client.send_message(
...     conversation,
...     sender,
...     message_parts,
...     notification=notification,
... )
>>> message_resp.recipient_status
{u'bob': u'sent', u'alice': u'read'}
>>> message_resp.sender
<LayerClient.Sender "None" (id: alice)>
>>> message_resp.conversation.participants
[]
>>> message_resp.conversation = client.get_conversation(
...     message_resp.conversation.uuid()
... )
>>> message_resp.conversation.participants
[u'alice', u'bob']
>>>
```

**Closed as completed** 2016-07-03 00:47 UTC
